//
//  UILable+ALayout.h
//  ALayout
//
//  Created by splendourbell on 2017/4/11.
//  Copyright © 2017年 ajja.sdjkf.sd. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UILabel(ALayout)

@end

#define TextView_editable                               @"android:editable"
#define TextView_digits                                 @"android:digits"
#define TextView_autoText                               @"android:autoText"
#define TextView_bufferType                             @"android:bufferType"
#define TextView_selectAllOnFocus                       @"android:selectAllOnFocus"
#define TextView_autoLink                               @"android:autoLink"
#define TextView_linksClickable                         @"android:linksClickable"
#define TextView_drawableLeft                           @"android:drawableLeft"
#define TextView_drawableTop                            @"android:drawableTop"
#define TextView_drawableRight                          @"android:drawableRight"
#define TextView_drawableBottom                         @"android:drawableBottom"
#define TextView_drawableStart                          @"android:drawableStart"
#define TextView_drawableEnd                            @"android:drawableEnd"
#define TextView_drawableTint                           @"android:drawableTint"
#define TextView_drawableTintMode                       @"android:drawableTintMode"
#define TextView_drawablePadding                        @"android:drawablePadding"
#define TextView_maxLines                               @"android:maxLines"
#define TextView_maxHeight                              @"android:maxHeight"
#define TextView_lines                                  @"android:lines"
#define TextView_height                                 @"android:height"
#define TextView_minLines                               @"android:minLines"
#define TextView_minHeight                              @"android:minHeight"
#define TextView_maxWidth                               @"android:maxWidth"
#define TextView_ems                                    @"android:ems"
#define TextView_width                                  @"android:width"
#define TextView_minEms                                 @"android:minEms"
#define TextView_minWidth                               @"android:minWidth"
#define TextView_gravity                                @"android:gravity"
#define TextView_hint                                   @"android:hint"
#define TextView_text                                   @"android:text"
#define TextView_scrollHorizontally                     @"android:scrollHorizontally"
#define TextView_singleLine                             @"android:singleLine"
#define TextView_ellipsize                              @"android:ellipsize"
#define TextView_marqueeRepeatLimit                     @"android:marqueeRepeatLimit"
#define TextView_includeFontPadding                     @"android:includeFontPadding"
#define TextView_cursorVisible                          @"android:cursorVisible"
#define TextView_maxLength                              @"android:maxLength"
#define TextView_textScaleX                             @"android:textScaleX"
#define TextView_freezesText                            @"android:freezesText"
#define TextView_shadowColor                            @"android:shadowColor"
#define TextView_shadowDx                               @"android:shadowDx"
#define TextView_shadowDy                               @"android:shadowDy"
#define TextView_shadowRadius                           @"android:shadowRadius"
#define TextView_enabled                                @"android:enabled"
#define TextView_textColorHighlight                     @"android:textColorHighlight"
#define TextView_textColor                              @"android:textColor"
#define TextView_textColorHint                          @"android:textColorHint"
#define TextView_textColorLink                          @"android:textColorLink"
#define TextView_textSize                               @"android:textSize"
#define TextView_typeface                               @"android:typeface"
#define TextView_textStyle                              @"android:textStyle"
#define TextView_fontFamily                             @"android:fontFamily"
#define TextView_password                               @"android:password"
#define TextView_lineSpacingExtra                       @"android:lineSpacingExtra"
#define TextView_lineSpacingMultiplier                  @"android:lineSpacingMultiplier"
#define TextView_inputType                              @"android:inputType"
#define TextView_allowUndo                              @"android:allowUndo"
#define TextView_imeOptions                             @"android:imeOptions"
#define TextView_imeActionLabel                         @"android:imeActionLabel"
#define TextView_imeActionId                            @"android:imeActionId"
#define TextView_privateImeOptions                      @"android:privateImeOptions"
#define TextView_editorExtras                           @"android:editorExtras"
#define TextView_textCursorDrawable                     @"android:textCursorDrawable"
#define TextView_textSelectHandleLeft                   @"android:textSelectHandleLeft"
#define TextView_textSelectHandleRight                  @"android:textSelectHandleRight"
#define TextView_textSelectHandle                       @"android:textSelectHandle"
#define TextView_textEditSuggestionItemLayout           @"android:textEditSuggestionItemLayout"
#define TextView_textEditSuggestionContainerLayout      @"android:textEditSuggestionContainerLayout"
#define TextView_textEditSuggestionHighlightStyle       @"android:textEditSuggestionHighlightStyle"
#define TextView_textIsSelectable                       @"android:textIsSelectable"
#define TextView_textAllCaps                            @"android:textAllCaps"
#define TextView_elegantTextHeight                      @"android:elegantTextHeight"
#define TextView_letterSpacing                          @"android:letterSpacing"
#define TextView_fontFeatureSettings                    @"android:fontFeatureSettings"
#define TextView_breakStrategy                          @"android:breakStrategy"
#define TextView_hyphenationFrequency                   @"android:hyphenationFrequency"



